"""Code generator stub for future phases."""


def generate_cpp(ir, source_line_count: int) -> str:
    """Generate deterministic legal C++ scaffold output."""
    _ = ir
    return (
        "// Auto-generated by listing_to_cpp\n"
        "#include <cstdint>\n\n"
        "namespace converted {\n"
        f"constexpr std::uint32_t generated_from_lines = {source_line_count};\n"
        "}  // namespace converted\n"
    )
