from pathlib import Path

from listing_to_cpp.converter import convert_listing_to_cpp


def expected_scaffold(source_line_count: int) -> str:
    return (
        "// Auto-generated by listing_to_cpp\n"
        "#include <cstdint>\n\n"
        "namespace converted {\n"
        f"constexpr std::uint32_t generated_from_lines = {source_line_count};\n"
        "}  // namespace converted\n"
    )


def test_converter_writes_expected_scaffold_with_trailing_newline(tmp_path: Path):
    input_path = tmp_path / "input.lst"
    output_path = tmp_path / "out.cpp"
    input_path.write_text("LINE A\nLINE B\n", encoding="ascii")

    convert_listing_to_cpp(input_path, output_path)

    assert output_path.exists()
    assert output_path.read_text(encoding="ascii") == expected_scaffold(2)


def test_converter_counts_logical_lines_without_trailing_newline(tmp_path: Path):
    input_path = tmp_path / "input.lst"
    output_path = tmp_path / "out.cpp"
    input_path.write_text("LINE A\nLINE B", encoding="ascii")

    convert_listing_to_cpp(input_path, output_path)

    assert output_path.read_text(encoding="ascii") == expected_scaffold(2)


def test_converter_is_byte_deterministic_across_repeated_runs(tmp_path: Path):
    input_path = tmp_path / "input.lst"
    output_path_first = tmp_path / "out_first.cpp"
    output_path_second = tmp_path / "out_second.cpp"
    input_path.write_text("LINE A\nLINE B\n", encoding="ascii")

    convert_listing_to_cpp(input_path, output_path_first)
    convert_listing_to_cpp(input_path, output_path_second)

    assert output_path_first.read_bytes() == output_path_second.read_bytes()
    assert output_path_first.read_text(encoding="ascii") == expected_scaffold(2)
