from pathlib import Path

from listing_to_cpp.converter import convert_listing_to_cpp
from listing_to_cpp.ir import build_ir
from listing_to_cpp.parser import parse_listing


def expected_scaffold(source_line_count: int) -> str:
    return (
        "// Auto-generated by listing_to_cpp\n"
        "#include <cstdint>\n"
        "#include <cstdio>\n"
        "\n"
        "namespace converted {\n"
        "\n"
        "// I/O shim interface (implementation provided by caller)\n"
        "extern std::uint8_t io_read(std::uint16_t addr);\n"
        "extern void io_write(std::uint16_t addr, std::uint8_t val);\n"
        "extern std::uint8_t mem_read(std::uint16_t addr);\n"
        "extern void mem_write(std::uint16_t addr, std::uint8_t val);\n"
        "\n"
        "// 6502 machine context\n"
        "struct Context {\n"
        "    std::uint8_t A{0};\n"
        "    std::uint8_t X{0};\n"
        "    std::uint8_t Y{0};\n"
        "    std::uint8_t SP{0xFFU};\n"
        "    std::uint8_t P{0};\n"
        "};\n"
        "\n"
        "void run(Context& ctx);\n"
        "\n"
        "void run(Context& ctx) {\n"
        "    return;\n"
        "}\n"
        "\n"
        f"constexpr std::uint32_t generated_from_lines = {source_line_count};\n"
        "\n"
        "}  // namespace converted\n"
    )


def test_build_ir_resolves_equ_symbols_to_numeric_values():
    listing_text = """SCREEN EQU $C000
COUNT EQU 16
HERE EQU *
"""

    parsed = parse_listing(listing_text)
    ir = build_ir(parsed)

    assert ir["symbols"]["SCREEN"]["value"] == 0xC000
    assert ir["symbols"]["COUNT"]["value"] == 16
    assert ir["symbols"]["HERE"]["value"] is None
    assert ir["symbols"]["HERE"]["is_current_location_alias"] is True


def test_build_ir_detects_explicit_c000_cfff_accesses_direct_and_symbolic():
    listing_text = """SCREEN EQU $C000
1234  8D 00 C0             STA   $C000
1237  AD 00 C0             LDA   SCREEN
"""

    parsed = parse_listing(listing_text)
    ir = build_ir(parsed)

    assert len(ir["instructions"]) == 2
    assert ir["io_accesses"] == [
        {
            "line": 2,
            "mnemonic": "STA",
            "operand": "$C000",
            "source": "direct",
            "resolved_address": 0xC000,
            "classification": "explicit_c000_cfff",
        },
        {
            "line": 3,
            "mnemonic": "LDA",
            "operand": "SCREEN",
            "source": "symbolic",
            "resolved_address": 0xC000,
            "classification": "explicit_c000_cfff",
        },
    ]


def test_build_ir_detects_explicit_indexed_c000_cfff_accesses_direct_and_symbolic():
    listing_text = """SCREEN EQU $C000
1234  BD 00 C0             LDA   $C000,X
1237  B9 10 C0             LDA   $C010,Y
123A  BD 00 C0             LDA   0xC000,X
123D  B9 00 C0             LDA   SCREEN,Y
"""

    parsed = parse_listing(listing_text)
    ir = build_ir(parsed)

    assert len(ir["instructions"]) == 4
    assert ir["io_accesses"] == [
        {
            "line": 2,
            "mnemonic": "LDA",
            "operand": "$C000,X",
            "source": "direct",
            "resolved_address": 0xC000,
            "classification": "explicit_c000_cfff",
        },
        {
            "line": 3,
            "mnemonic": "LDA",
            "operand": "$C010,Y",
            "source": "direct",
            "resolved_address": 0xC010,
            "classification": "explicit_c000_cfff",
        },
        {
            "line": 4,
            "mnemonic": "LDA",
            "operand": "0xC000,X",
            "source": "direct",
            "resolved_address": 0xC000,
            "classification": "explicit_c000_cfff",
        },
        {
            "line": 5,
            "mnemonic": "LDA",
            "operand": "SCREEN,Y",
            "source": "symbolic",
            "resolved_address": 0xC000,
            "classification": "explicit_c000_cfff",
        },
    ]


def test_build_ir_resolves_symbols_case_insensitively_for_equ_and_operands():
    listing_text = """ScReEn EQU $C000
1234  AD 00 C0             LDA   SCREEN
1237  B9 00 C0             LDA   screen,Y
"""

    parsed = parse_listing(listing_text)
    ir = build_ir(parsed)

    assert ir["symbols"]["ScReEn"]["value"] == 0xC000
    assert ir["io_accesses"] == [
        {
            "line": 2,
            "mnemonic": "LDA",
            "operand": "SCREEN",
            "source": "symbolic",
            "resolved_address": 0xC000,
            "classification": "explicit_c000_cfff",
        },
        {
            "line": 3,
            "mnemonic": "LDA",
            "operand": "screen,Y",
            "source": "symbolic",
            "resolved_address": 0xC000,
            "classification": "explicit_c000_cfff",
        },
    ]


def test_build_ir_tags_unresolved_indirect_accesses_as_uncertain_warning():
    listing_text = """1000  B1 20                LDA   ($20),Y
"""

    parsed = parse_listing(listing_text)
    ir = build_ir(parsed)

    assert len(ir["instructions"]) == 1
    assert ir["warnings"] == [
        {
            "kind": "uncertain_indirect_access",
            "line": 1,
            "mnemonic": "LDA",
            "operand": "($20),Y",
            "message": "Unresolved indirect memory access; cannot determine whether it targets 0xC000-0xCFFF.",
        }
    ]


def test_converter_writes_expected_scaffold_with_trailing_newline(tmp_path: Path):
    input_path = tmp_path / "input.lst"
    output_path = tmp_path / "out.cpp"
    input_path.write_text("LINE A\nLINE B\n", encoding="ascii")

    convert_listing_to_cpp(input_path, output_path)

    assert output_path.exists()
    assert output_path.read_text(encoding="ascii") == expected_scaffold(2)


def test_converter_counts_logical_lines_without_trailing_newline(tmp_path: Path):
    input_path = tmp_path / "input.lst"
    output_path = tmp_path / "out.cpp"
    input_path.write_text("LINE A\nLINE B", encoding="ascii")

    convert_listing_to_cpp(input_path, output_path)

    assert output_path.read_text(encoding="ascii") == expected_scaffold(2)


def test_converter_is_byte_deterministic_across_repeated_runs(tmp_path: Path):
    input_path = tmp_path / "input.lst"
    output_path_first = tmp_path / "out_first.cpp"
    output_path_second = tmp_path / "out_second.cpp"
    input_path.write_text("LINE A\nLINE B\n", encoding="ascii")

    convert_listing_to_cpp(input_path, output_path_first)
    convert_listing_to_cpp(input_path, output_path_second)

    assert output_path_first.read_bytes() == output_path_second.read_bytes()
    assert output_path_first.read_text(encoding="ascii") == expected_scaffold(2)


def test_converter_ei_listing_emits_non_empty_run_body(tmp_path: Path):
    input_path = Path("example/EI.LST")
    output_path = tmp_path / "ei_out.cpp"

    convert_listing_to_cpp(input_path, output_path)

    generated = output_path.read_text(encoding="ascii")
    assert "void run(Context& ctx" in generated
    assert "/* LDX #$F0 */" in generated
